version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    working_directory: ~/application

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Export key
          command: echo $BASE64_KEY | base64 -d > key.pem

      - run:
          name: Export cert
          command: echo $BASE64_CERT | base64 -d > cert.pem

      - run:
          name: Convert to PKCS12
          command: openssl pkcs12 -export -out src/main/resources/key.p12 -inkey key.pem -in cert.pem -passout pass:$PKCS12_PASS -name shopdb

      - run:
          name: Package JAR
          command: mvn clean package

      - run:
          name: Deploy to server
          command: scp -o StrictHostKeyChecking=no -r /home/circleci/application/target/* $HOST:~/applications/mcstats-us-backend